//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CU_Employee()
        {
            this.CU_Employee_RoleProgram = new HashSet<CU_Employee_RoleProgram>();
            this.CU_Log = new HashSet<CU_Log>();
            this.DUC_Log = new HashSet<DUC_Log>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int IdJob { get; set; }
        public string Mobile { get; set; }
        public bool Gender { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public bool IsActive { get; set; }
        public int IdDepartment { get; set; }
        public int IdHeadDepartment { get; set; }
        public bool IsTrainee { get; set; }
        public string Phone { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastVisitTime { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> IdEmployeeCategory { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual CU_Branch CU_Branch { get; set; }
        public virtual CU_Department CU_Department { get; set; }
        public virtual CU_EmployeeCategory CU_EmployeeCategory { get; set; }
        public virtual CU_HeadDepartment CU_HeadDepartment { get; set; }
        public virtual CU_Job CU_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CU_Employee_RoleProgram> CU_Employee_RoleProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CU_Log> CU_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Log> DUC_Log { get; set; }
    }
}
