//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CU_Page()
        {
            this.CU_Log = new HashSet<CU_Log>();
            this.CU_Role_Page = new HashSet<CU_Role_Page>();
            this.DUC_Log = new HashSet<DUC_Log>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public int IdProgram { get; set; }
        public bool IsDeleted { get; set; }
        public string Actions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CU_Log> CU_Log { get; set; }
        public virtual CU_Program CU_Program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CU_Role_Page> CU_Role_Page { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Log> DUC_Log { get; set; }
    }
}
