//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_Role_Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CU_Role_Program()
        {
            this.CU_Employee_RoleProgram = new HashSet<CU_Employee_RoleProgram>();
            this.CU_Role_Page = new HashSet<CU_Role_Page>();
        }
    
        public int ID { get; set; }
        public int IdRole { get; set; }
        public int IdProgram { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CU_Employee_RoleProgram> CU_Employee_RoleProgram { get; set; }
        public virtual CU_Program CU_Program { get; set; }
        public virtual CU_Role CU_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CU_Role_Page> CU_Role_Page { get; set; }
    }
}
