//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QvApp_RawdaDeductionEntities3 : DbContext
    {
        public QvApp_RawdaDeductionEntities3()
            : base("name=QvApp_RawdaDeductionEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CU_Action> CU_Action { get; set; }
        public virtual DbSet<CU_Branch> CU_Branch { get; set; }
        public virtual DbSet<CU_Department> CU_Department { get; set; }
        public virtual DbSet<CU_Employee> CU_Employee { get; set; }
        public virtual DbSet<CU_Employee_Role> CU_Employee_Role { get; set; }
        public virtual DbSet<CU_Employee_RoleProgram> CU_Employee_RoleProgram { get; set; }
        public virtual DbSet<CU_EmployeeCategory> CU_EmployeeCategory { get; set; }
        public virtual DbSet<CU_Goal> CU_Goal { get; set; }
        public virtual DbSet<CU_HeadDepartment> CU_HeadDepartment { get; set; }
        public virtual DbSet<CU_Job> CU_Job { get; set; }
        public virtual DbSet<CU_Log> CU_Log { get; set; }
        public virtual DbSet<CU_Page> CU_Page { get; set; }
        public virtual DbSet<CU_Program> CU_Program { get; set; }
        public virtual DbSet<CU_Role> CU_Role { get; set; }
        public virtual DbSet<CU_Role_Page> CU_Role_Page { get; set; }
        public virtual DbSet<CU_Role_Program> CU_Role_Program { get; set; }
        public virtual DbSet<DUC_Bank> DUC_Bank { get; set; }
        public virtual DbSet<DUC_BankAccount> DUC_BankAccount { get; set; }
        public virtual DbSet<DUC_BankDirectForm> DUC_BankDirectForm { get; set; }
        public virtual DbSet<DUC_BankRepresentative> DUC_BankRepresentative { get; set; }
        public virtual DbSet<DUC_BankSheet> DUC_BankSheet { get; set; }
        public virtual DbSet<DUC_BankSheetSetting> DUC_BankSheetSetting { get; set; }
        public virtual DbSet<DUC_BonusPercentage> DUC_BonusPercentage { get; set; }
        public virtual DbSet<DUC_City> DUC_City { get; set; }
        public virtual DbSet<DUC_Donor> DUC_Donor { get; set; }
        public virtual DbSet<DUC_DonorBankAccount> DUC_DonorBankAccount { get; set; }
        public virtual DbSet<DUC_DonorPaymentAmount> DUC_DonorPaymentAmount { get; set; }
        public virtual DbSet<DUC_Form> DUC_Form { get; set; }
        public virtual DbSet<DUC_FormBatchesAmount> DUC_FormBatchesAmount { get; set; }
        public virtual DbSet<DUC_FormDelayedReason> DUC_FormDelayedReason { get; set; }
        public virtual DbSet<DUC_FormDirectedTo> DUC_FormDirectedTo { get; set; }
        public virtual DbSet<DUC_FormPackageProject> DUC_FormPackageProject { get; set; }
        public virtual DbSet<DUC_FormStatus> DUC_FormStatus { get; set; }
        public virtual DbSet<DUC_FormTrippedReason> DUC_FormTrippedReason { get; set; }
        public virtual DbSet<DUC_GalleryType> DUC_GalleryType { get; set; }
        public virtual DbSet<DUC_Log> DUC_Log { get; set; }
        public virtual DbSet<DUC_Notification> DUC_Notification { get; set; }
        public virtual DbSet<DUC_NotificationType> DUC_NotificationType { get; set; }
        public virtual DbSet<DUC_NotificationUser> DUC_NotificationUser { get; set; }
        public virtual DbSet<DUC_Package> DUC_Package { get; set; }
        public virtual DbSet<DUC_PackageProjectDetail> DUC_PackageProjectDetail { get; set; }
        public virtual DbSet<DUC_PackageVersion> DUC_PackageVersion { get; set; }
        public virtual DbSet<DUC_PaymentStatus> DUC_PaymentStatus { get; set; }
        public virtual DbSet<DUC_PaymentType> DUC_PaymentType { get; set; }
        public virtual DbSet<DUC_Project> DUC_Project { get; set; }
        public virtual DbSet<DUC_ProjectAchievements> DUC_ProjectAchievements { get; set; }
        public virtual DbSet<DUC_ProjectGallery> DUC_ProjectGallery { get; set; }
        public virtual DbSet<DUC_Representative> DUC_Representative { get; set; }
        public virtual DbSet<DUC_RepresentativeBonus> DUC_RepresentativeBonus { get; set; }
        public virtual DbSet<DUC_RepresentativeType> DUC_RepresentativeType { get; set; }
        public virtual DbSet<DUC_SimilarProjects> DUC_SimilarProjects { get; set; }
        public virtual DbSet<DUC_State> DUC_State { get; set; }
        public virtual DbSet<DUC_Unit> DUC_Unit { get; set; }
    
        public virtual ObjectResult<usp_FormsEndIn_Result> usp_FormsEndIn(Nullable<int> endDays)
        {
            var endDaysParameter = endDays.HasValue ?
                new ObjectParameter("EndDays", endDays) :
                new ObjectParameter("EndDays", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_FormsEndIn_Result>("usp_FormsEndIn", endDaysParameter);
        }
    
        public virtual ObjectResult<usp_PopularProjects_Result> usp_PopularProjects(string projectName, Nullable<bool> projectIsCompleted)
        {
            var projectNameParameter = projectName != null ?
                new ObjectParameter("ProjectName", projectName) :
                new ObjectParameter("ProjectName", typeof(string));
    
            var projectIsCompletedParameter = projectIsCompleted.HasValue ?
                new ObjectParameter("ProjectIsCompleted", projectIsCompleted) :
                new ObjectParameter("ProjectIsCompleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PopularProjects_Result>("usp_PopularProjects", projectNameParameter, projectIsCompletedParameter);
        }
    }
}
