//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_BankAccount()
        {
            this.DUC_BankSheet = new HashSet<DUC_BankSheet>();
            this.DUC_DonorPaymentAmount = new HashSet<DUC_DonorPaymentAmount>();
        }
    
        public int ID { get; set; }
        public int BankID { get; set; }
        public string BankAccountNumber { get; set; }
    
        public virtual DUC_Bank DUC_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_BankSheet> DUC_BankSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_DonorPaymentAmount> DUC_DonorPaymentAmount { get; set; }
    }
}
