//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_PackageVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_PackageVersion()
        {
            this.DUC_Form = new HashSet<DUC_Form>();
            this.DUC_PackageProjectDetail = new HashSet<DUC_PackageProjectDetail>();
        }
    
        public int ID { get; set; }
        public int PackageID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsCurrent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Form> DUC_Form { get; set; }
        public virtual DUC_Package DUC_Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_PackageProjectDetail> DUC_PackageProjectDetail { get; set; }
    }
}
