//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_SimilarProjects
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int SimilarProjectID { get; set; }
    
        public virtual DUC_Project DUC_Project { get; set; }
        public virtual DUC_Project DUC_Project1 { get; set; }
    }
}
