//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_RepresentativeBonus
    {
        public int ID { get; set; }
        public Nullable<int> FormID { get; set; }
        public int BankRepresentativeID { get; set; }
        public double BonusAmount { get; set; }
        public System.DateTime BonusDeliveryDate { get; set; }
        public string BonusAttatchment { get; set; }
    
        public virtual DUC_BankRepresentative DUC_BankRepresentative { get; set; }
        public virtual DUC_Form DUC_Form { get; set; }
    }
}
