//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_Donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_Donor()
        {
            this.DUC_DonorBankAccount = new HashSet<DUC_DonorBankAccount>();
            this.DUC_Form = new HashSet<DUC_Form>();
            this.DUC_Notification = new HashSet<DUC_Notification>();
            this.DUC_NotificationUser = new HashSet<DUC_NotificationUser>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Workplace { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> StateID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<bool> IsDirectFromBank { get; set; }
        public bool IsDelete { get; set; }
        public bool IsSite { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public bool IsActiveOnSite { get; set; }
        public string ActivationCode { get; set; }
    
        public virtual DUC_City DUC_City { get; set; }
        public virtual DUC_State DUC_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_DonorBankAccount> DUC_DonorBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Form> DUC_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Notification> DUC_Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_NotificationUser> DUC_NotificationUser { get; set; }
    }
}
