//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_BankRepresentative
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_BankRepresentative()
        {
            this.DUC_Form = new HashSet<DUC_Form>();
            this.DUC_Form1 = new HashSet<DUC_Form>();
            this.DUC_RepresentativeBonus = new HashSet<DUC_RepresentativeBonus>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BankID { get; set; }
        public int RepresentativeTypeID { get; set; }
        public int RepresentativeID { get; set; }
    
        public virtual DUC_Bank DUC_Bank { get; set; }
        public virtual DUC_Representative DUC_Representative { get; set; }
        public virtual DUC_RepresentativeType DUC_RepresentativeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Form> DUC_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Form> DUC_Form1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_RepresentativeBonus> DUC_RepresentativeBonus { get; set; }
    }
}
