//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_DonorPaymentAmount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_DonorPaymentAmount()
        {
            this.DUC_FormBatchesAmount = new HashSet<DUC_FormBatchesAmount>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BankSheetID { get; set; }
        public Nullable<int> DonorBankAccountID { get; set; }
        public Nullable<int> BankAccountID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual DUC_BankAccount DUC_BankAccount { get; set; }
        public virtual DUC_BankSheet DUC_BankSheet { get; set; }
        public virtual DUC_DonorBankAccount DUC_DonorBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_FormBatchesAmount> DUC_FormBatchesAmount { get; set; }
    }
}
