//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_BankSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_BankSheet()
        {
            this.DUC_BankDirectForm = new HashSet<DUC_BankDirectForm>();
            this.DUC_DonorPaymentAmount = new HashSet<DUC_DonorPaymentAmount>();
        }
    
        public int ID { get; set; }
        public int BankID { get; set; }
        public int BankAccountID { get; set; }
        public string Path { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
    
        public virtual DUC_Bank DUC_Bank { get; set; }
        public virtual DUC_BankAccount DUC_BankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_BankDirectForm> DUC_BankDirectForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_DonorPaymentAmount> DUC_DonorPaymentAmount { get; set; }
    }
}
