//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_Project()
        {
            this.DUC_Form = new HashSet<DUC_Form>();
            this.DUC_FormPackageProject = new HashSet<DUC_FormPackageProject>();
            this.DUC_FormPackageProject1 = new HashSet<DUC_FormPackageProject>();
            this.DUC_PackageProjectDetail = new HashSet<DUC_PackageProjectDetail>();
            this.DUC_ProjectAchievements = new HashSet<DUC_ProjectAchievements>();
            this.DUC_ProjectGallery = new HashSet<DUC_ProjectGallery>();
            this.DUC_SimilarProjects = new HashSet<DUC_SimilarProjects>();
            this.DUC_SimilarProjects1 = new HashSet<DUC_SimilarProjects>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Target { get; set; }
        public Nullable<double> TargetAchieved { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<bool> IsImportant { get; set; }
        public bool IsCompleted { get; set; }
        public string SeoData { get; set; }
        public string SeoTargetKey { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoMetaKey { get; set; }
        public string SeoUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Form> DUC_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_FormPackageProject> DUC_FormPackageProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_FormPackageProject> DUC_FormPackageProject1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_PackageProjectDetail> DUC_PackageProjectDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_ProjectAchievements> DUC_ProjectAchievements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_ProjectGallery> DUC_ProjectGallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_SimilarProjects> DUC_SimilarProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_SimilarProjects> DUC_SimilarProjects1 { get; set; }
    }
}
