//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_Form()
        {
            this.DUC_Form1 = new HashSet<DUC_Form>();
            this.DUC_FormBatchesAmount = new HashSet<DUC_FormBatchesAmount>();
            this.DUC_FormPackageProject = new HashSet<DUC_FormPackageProject>();
            this.DUC_RepresentativeBonus = new HashSet<DUC_RepresentativeBonus>();
        }
    
        public int ID { get; set; }
        public int DonorID { get; set; }
        public int DonorBankAccountID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> FormDirectedToID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<bool> IsFreePackage { get; set; }
        public Nullable<int> PackageVersionID { get; set; }
        public Nullable<int> BankRepresentativeID { get; set; }
        public Nullable<int> BankApprovalRepresentativeID { get; set; }
        public bool IsLive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> NumOfBatch { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> FormStatusID { get; set; }
        public Nullable<int> TrippedReasonID { get; set; }
        public Nullable<int> DelayedReasonID { get; set; }
        public Nullable<int> PaymentStatusID { get; set; }
        public double Amount { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public bool IsSite { get; set; }
        public Nullable<bool> IsDirectFromBank { get; set; }
        public Nullable<bool> IsRenewed { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool IsDelete { get; set; }
        public string FormPurpose { get; set; }
        public string RegisterationAttatchment { get; set; }
        public string BankApprovalAttatchment { get; set; }
        public Nullable<bool> BankBonusIsDelivered { get; set; }
        public Nullable<bool> BankApprovalBonusIsDelivered { get; set; }
        public Nullable<bool> IsPrintedFormLetter { get; set; }
        public Nullable<bool> IsPrintedBankLetter { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    
        public virtual DUC_BankRepresentative DUC_BankRepresentative { get; set; }
        public virtual DUC_BankRepresentative DUC_BankRepresentative1 { get; set; }
        public virtual DUC_Donor DUC_Donor { get; set; }
        public virtual DUC_DonorBankAccount DUC_DonorBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Form> DUC_Form1 { get; set; }
        public virtual DUC_Form DUC_Form2 { get; set; }
        public virtual DUC_FormDirectedTo DUC_FormDirectedTo { get; set; }
        public virtual DUC_FormStatus DUC_FormStatus { get; set; }
        public virtual DUC_FormTrippedReason DUC_FormTrippedReason { get; set; }
        public virtual DUC_PackageVersion DUC_PackageVersion { get; set; }
        public virtual DUC_PaymentStatus DUC_PaymentStatus { get; set; }
        public virtual DUC_PaymentType DUC_PaymentType { get; set; }
        public virtual DUC_Project DUC_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_FormBatchesAmount> DUC_FormBatchesAmount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_FormPackageProject> DUC_FormPackageProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_RepresentativeBonus> DUC_RepresentativeBonus { get; set; }
    }
}
