//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_FormBatchesAmount
    {
        public int ID { get; set; }
        public int FormID { get; set; }
        public System.DateTime BatchStartDate { get; set; }
        public Nullable<System.DateTime> BatchEndDate { get; set; }
        public Nullable<int> DonorPaymentAmountID { get; set; }
        public Nullable<double> AmountDue { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public bool IsSendSMS { get; set; }
    
        public virtual DUC_DonorPaymentAmount DUC_DonorPaymentAmount { get; set; }
        public virtual DUC_Form DUC_Form { get; set; }
    }
}
