//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_BankSheetSetting
    {
        public int ID { get; set; }
        public int BankID { get; set; }
        public string BankAccountCell { get; set; }
        public string DurationCell { get; set; }
        public string DurationStartCell { get; set; }
        public string DurationEndCell { get; set; }
        public string FirstColumnCell { get; set; }
        public string LastColumnCell { get; set; }
        public Nullable<int> DataSheetNum { get; set; }
    }
}
