//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_DonorBankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_DonorBankAccount()
        {
            this.DUC_DonorPaymentAmount = new HashSet<DUC_DonorPaymentAmount>();
            this.DUC_Form = new HashSet<DUC_Form>();
        }
    
        public int ID { get; set; }
        public int DonorID { get; set; }
        public int BankID { get; set; }
        public string DonorAccountNumber { get; set; }
    
        public virtual DUC_Bank DUC_Bank { get; set; }
        public virtual DUC_Donor DUC_Donor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_DonorPaymentAmount> DUC_DonorPaymentAmount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_Form> DUC_Form { get; set; }
    }
}
