//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUC_Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUC_Notification()
        {
            this.DUC_NotificationUser = new HashSet<DUC_NotificationUser>();
        }
    
        public int NotificationId { get; set; }
        public Nullable<int> NotificationTypeId { get; set; }
        public Nullable<int> From { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual DUC_Donor DUC_Donor { get; set; }
        public virtual DUC_NotificationType DUC_NotificationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUC_NotificationUser> DUC_NotificationUser { get; set; }
    }
}
